### ISSUE TITLE
Expression Pedal Controller Labels Off by 1

### ISSUE THREAD

**Issue by sbmechanics** [griphiam/gcpeditor#11]
Issue #7 is fixed (this issue is unrelated to CSV)- but the labels for Preset Pedal Configuration are Off by 1.  For example:
Preset Pedal Configuration - Pedal 1 MIDI Definition - MIDI Controller 2 changes to CC 1 on the GCP (should be CC 2) when sending to device, 
Preset Pedal Configuration - Pedal 1 MIDI Definition - MIDI Controller 3 changes to CC 2 (should be CC 3) when sending to device.

**Comment by sbmechanics** [comment]
Line 478, js/main.js
`  $(sprintf('<option value="%d">MIDI Controller #%d</option>', i, i-2)).appendTo($sel);`
Appears that last %d text within <option> tag needs -1.

**Comment by markphilpot** [comment]
For clarification: Is it the UI (i.e. the label) that is wrong or the value that's displayed on the controller?

This is the definition of that field in the sysex spec:

`0=off, 1=Pitchbend, 2=Aftertouch, 3..123=MIDI Controller# - 3 except when Device#=8 and VCA Exists, then:0=off, 1=VCA Stereo, 2=VCA Pan, 3=VCA left, 4=VCA Right, >4=off`

So I set `Pedal 1 MIDI Definition` to 3 in the sysex file, what does the GCP display (what is the lowest `MIDI Controller #`?  If it's just the UI, then I can update the label to be `i-3` instead of `i-2`

**Comment by sbmechanics** [comment]
Appears that changing to 
` $(sprintf('<option value="%d">MIDI Controller #%d</option>', i, i-3)).appendTo($sel);'
will resolve.  Just tested.
Per your question, label was wrong.

**Comment by markphilpot** [comment]
Cool.  That's easy enough.  One sec and I'll push up a PR

**Comment by sbmechanics** [comment]
I downloaded a clone and am looking at non-UI stuff (I can't HTML or CSS).  Thanks.
